<a href="https://colab.research.google.com/github/brianstoner/Data-Prep-and-Mgmt/blob/main/Copy_of_danl_m1_hw3_Stoner_Brian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd

In [32]:
nyc_payroll = pd.read_csv('https://bcdanl.github.io/data/nyc_payroll_2022_2023.csv')

In [ ]:
nyc_payroll.info()

In [ ]:
nyc_payroll.sort_values(["Agency Name"])

### Question 1
- *Select “First Name”, “Last Name”, “Base Salary”, and “Total OT Paid”, then sort these selected variables by “Base Salary” in descending order and display the top 10 entries.*

In [4]:
(
nyc_payroll[ ['First Name', 'Last Name', 'Base Salary', 'Total OT Paid' ] ]
  .sort_values(['Base Salary'], ascending=False)
  .head(10)
)

     First Name  Last Name  Base Salary  Total OT Paid
433     MICHAEL    BIMONTE     233094.0            0.0
61       BEDROS  BOODANIAN     215861.0            0.0
1378     ARVIND     SOHONI     215000.0            0.0
1469     ANDREW     KAPLAN     195000.0            0.0
73     VICTORIA       RICE     187530.0            0.0
858      JOSEPH   PILEWSKI     180450.0            0.0
1379     SAMUEL      DAVID     180000.0            0.0
425      KARINA    JIMENEZ     178000.0            0.0
74     JOYCELYN       NEDD     177113.0            0.0
352    JEANETTE     VARGAS     176947.0            0.0

### Question 2
- *Create a new DataFrame that includes employees from the “DEPARTMENT OF EDUCATION ADMIN” agency where the variables are “First Name”, “Last Name”, “Title Description”, “Base Salary”, and “Total OT Paid”. Additionally, include a new variable “Total Compensation” which is the sum of “Base Salary” and “Total OT Paid”.*

In [47]:
# Add a variable to the dataframe that calculates total compensation
nyc_payroll['Total Compensation'] = nyc_payroll['Base Salary'] + nyc_payroll['Total OT Paid']
# Select only the required variables from the dataframe and assign them to a new (sub) dataframe
sub_nyc_payroll = nyc_payroll[['First Name', 'Last Name', 'Title Description', 'Agency Name', 'Base Salary', 'Total OT Paid', 'Total Compensation']]
# Set the index on a new column that will be useful for further data wrangling
sub_nyc_payroll.set_index("Agency Name", inplace = True)
# Extract observations where the agency name is DEPARTMENT OF EDUCATION ADMIN
sub_nyc_payroll.loc[ "DEPARTMENT OF EDUCATION ADMIN" ]

,First Name,Last Name,Title Description,Base Salary,Total OT Paid,Total Compensation
Agency Name,,,,,,
DEPARTMENT OF EDUCATION ADMIN,OSCAR,DAVIS,SUBSTANCE ABUSE PREVENTION & INTERVENTION SPEC...,53820.0,0.00,53820.00
DEPARTMENT OF EDUCATION ADMIN,JENNA,VARNAUSKAS,OCCUPATIONAL THERAPIST,75381.0,0.00,75381.00
DEPARTMENT OF EDUCATION ADMIN,CHRISTINA,GRANQUIST,PHYSICAL THERAPIST,80270.0,0.00,80270.00
DEPARTMENT OF EDUCATION ADMIN,SANDRA,QUIAH,COMMUNITY ASSOCIATE,55323.0,0.00,55323.00
DEPARTMENT OF EDUCATION ADMIN,SHATARA,EARL,PROCUREMENT ANALYST,62055.0,0.00,62055.00
...,...,...,...,...,...,...
DEPARTMENT OF EDUCATION ADMIN,DEISMOND,ROSA,COMMUNITY COORDINATOR,82170.0,1602.93,83772.93
DEPARTMENT OF EDUCATION ADMIN,SERIDE,READ,COMMUNITY COORDINATOR,67834.0,639.27,68473.27
DEPARTMENT OF EDUCATION ADMIN,ELISA,CORADO DERAS,COMMUNITY ASSISTANT,40765.0,0.00,40765.00
DEPARTMENT OF EDUCATION ADMIN,YAZMYN,YEARDE,SUBSTANCE ABUSE PREVENTION & INTERVENTION SPEC...,58811.0,0.00,58811.00
DEPARTMENT OF EDUCATION ADMIN,FOLASADE,AKINTUNDE,PHYSICAL THERAPIST,80730.0,0.00,80730.00