<a href="https://colab.research.google.com/github/brianstoner/Data-Prep-and-Mgmt/blob/main/danl_m1_exam_Stoner_Brian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
beer_mkts = pd.read_csv('https://bcdanl.github.io/data/beer_markets.csv')

In [3]:
from google.colab import data_table
data_table.enable_dataframe_formatter()

### Question 1
- *Find the top 5 beer markets in terms of the number of households that purchased beer.*
- *Find the top 5 beer markets in terms of the amount of total beer consumption.*

In [16]:
beer_mkts

Warning: total number of rows (73115) exceeds max_rows (20000). Falling back to pandas display.

,hh,_purchase_desc,quantity,brand,dollar_spent,beer_floz,price_per_floz,container,promo,market,...,age,employment,degree,cow,race,microwave,dishwasher,tvcable,singlefamilyhome,npeople
0,2000946,BUD LT BR CN 12P,1,BUD LIGHT,8.14,144.0,0.056528,CAN,False,RURAL ILLINOIS,...,50+,none,Grad,none/retired/student,white,True,True,premium,False,1
1,2003036,BUD LT BR CN 24P,1,BUD LIGHT,17.48,288.0,0.060694,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
2,2003036,BUD LT BR CN 24P,2,BUD LIGHT,33.92,576.0,0.058889,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
3,2003036,BUD LT BR CN 30P,2,BUD LIGHT,34.74,720.0,0.048250,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
4,2003036,BUD LT BR CN 36P,2,BUD LIGHT,40.48,864.0,0.046852,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73110,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,11.49,288.0,0.039896,CAN,True,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73111,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.97,288.0,0.034618,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73112,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.98,288.0,0.034653,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73113,9164033,NATURAL LT BR CN 30P,1,NATURAL LIGHT,12.98,360.0,0.036056,CAN,False,SACRAMENTO,...,50+,full,College,prof,hispanic,True,True,basic,True,5plus
73114,9164155,NATURAL LT BR CN 24P,1,NATURAL LIGHT,13.49,288.0,0.046840,CAN,False,JACKSONVILLE,...,50+,full,HS,labor/craft/military/farm,white,True,True,none,True,2

In [6]:
# Count the number of unique households by market
df = beer_mkts
count_by_market = df.groupby('market')['hh'].nunique()
count_by_market
# Sort descending and limit to top 5 markets by household values
top_markets = count_by_market.sort_values(ascending = False).head(5)
top_markets

market
TAMPA        345
CHICAGO      317
PHOENIX      310
ST. LOUIS    301
HOUSTON      269
Name: hh, dtype: int64

In [7]:
# Grouping by market, find the total consumtion by ounces in the beer_floz variable
consumption_by_market = df.groupby('market')['beer_floz'].sum()
consumption_by_market
# Sort values and limit to the top 5 results
top_markets = consumption_by_market.sort_values(ascending = False).head(5)
top_markets

market
TAMPA          890418.0
PHOENIX        675318.0
MIAMI          632684.0
SAN ANTONIO    631852.0
CHICAGO        558878.0
Name: beer_floz, dtype: float64

### Question 2
- *For households that purchased BUD LIGHT at least once, what fraction of households did purchase only BUD LIGHT?*

- *For households that purchased BUSCH LIGHT at least once, what fraction of households did purchase only BUSCH LIGHT?*

- *For households that purchased COORS LIGHT at least once, what fraction of households did purchase only COORS LIGHT?*

- *For households that purchased MILLER LITE at least once, what fraction of households did purchase only MILLER LITE?*

- *For households that purchased NATURAL LIGHT at least once, what fraction of households did purchase only NATURAL LIGHT?*

- *Which beer brand does have the largest proportion of such loyal consumers?*

In [15]:
# Filter the dataframe to households that bought the product at least once
bl_filtered = df[df['brand'] == 'BUD LIGHT']
all_households = df['hh'].unique()
# Group households that appear in the foltered dataframe
only_bud_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
# Calculate the fraction of households that bought at least once to all households
fraction_only_bud_light = len(only_bud_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only BUD LIGHT is: {fraction_only_bud_light:.2f}")
# Repeat the above code with the various values in the brand variable
bl_filtered = df[df['brand'] == 'BUSCH LIGHT']
all_households = df['hh'].unique()
only_busch_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_busch_light = len(only_busch_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only BUSCH LIGHT is: {fraction_only_busch_light:.2f}")

bl_filtered = df[df['brand'] == 'COORS LIGHT']
all_households = df['hh'].unique()
only_coors_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_coors_light = len(only_coors_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only COORS LIGHT is: {fraction_only_coors_light:.2f}")

bl_filtered = df[df['brand'] == 'MILLER LIGHT']
all_households = df['hh'].unique()
only_miller_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_miller_light = len(only_miller_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only MILLER LIGHT is: {fraction_only_miller_light:.2f}")

bl_filtered = df[df['brand'] == 'NATURAL LIGHT']
all_households = df['hh'].unique()
only_natural_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_natural_light = len(only_natural_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only NATURAL LIGHT is: {fraction_only_natural_light:.2f}")

The fraction of households that purchased only BUD LIGHT is: 0.30
The fraction of households that purchased only BUSCH LIGHT is: 0.05
The fraction of households that purchased only COORS LIGHT is: 0.19
The fraction of households that purchased only MILLER LIGHT is: 0.00
The fraction of households that purchased only NATURAL LIGHT is: 0.06

In [46]:
import numpy as np
paidsearch = pd.read_csv('https://bcdanl.github.io/data/paidsearch.csv')

### Question 3
- *Summarize the mean value of revenue for each group of search_stays_on and for each date.*

In [45]:
new_df = paidsearch
# Convert the date datatype from object to datetime
new_df['date'] = pd.to_datetime(new_df['date'])
# Group by search stays on and date for the mean value of revenue
mean_revenue_summary = round(new_df.groupby(['search_stays_on', 'date'])['revenue'].mean(), 2)
mean_revenue_summary

search_stays_on  date
0                2012-04-01     93650.68
                 2012-04-02    113057.92
                 2012-04-03    114255.77
                 2012-04-04    104836.69
                 2012-04-05    106881.59
                                 ...
1                2012-07-18    139383.76
                 2012-07-19    133239.08
                 2012-07-20    129653.84
                 2012-07-21    107194.27
                 2012-07-22    116001.55
Name: revenue, Length: 226, dtype: float64

### Question 4
- *Calculate the log difference between mean revenues in each group of search_stays_on. (This is the log of the average revenue in group of search_stays_on == 1 minus the log of the average revenue in group of search_stays_on == 0.)*

In [52]:
# Calculate the mean revenue for each of the search_stays_on groups
mean_revenue = new_df.groupby('search_stays_on')['revenue'].mean()
# Find the logarithm of the mean revenue for each group
log_mean_revenue = np.log(mean_revenue)
# Calculate the log difference
log_diff = log_mean_revenue.loc[1] - log_mean_revenue.loc[0]
print(f"The log difference between mean revenues for each group of search_stays_on is: {log_diff:.2f}")

The log difference between mean revenues for each group of search_stays_on is: 0.24

In [54]:
NFL2023_stuffs = pd.read_csv('https://bcdanl.github.io/data/NFL2023_stuffs.csv')

### Question 5
- *In DataFrame, NFL2023_stuffs, remove observations for which values of posteam is missing.*

In [55]:
nfl = NFL2023_stuffs

In [81]:
# View the dataframe and notice the value in index 0, posteam variable is NaN
nfl

Warning: total number of rows (49665) exceeds max_rows (20000). Falling back to pandas display.

,play_id,game_id,drive,week,posteam,qtr,down,half_seconds_remaining,pass,wp
0,1,2023_01_ARI_WAS,NaN,1,NaN,1,NaN,1800.0,0,0.546262
1,39,2023_01_ARI_WAS,1.0,1,WAS,1,NaN,1800.0,0,0.546262
2,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262
3,77,2023_01_ARI_WAS,1.0,1,WAS,1,2.0,1770.0,1,0.539621
4,102,2023_01_ARI_WAS,1.0,1,WAS,1,3.0,1735.0,0,0.555987
...,...,...,...,...,...,...,...,...,...,...
49660,4791,2023_22_SF_KC,26.0,22,KC,5,3.0,127.0,1,0.648316
49661,4813,2023_22_SF_KC,26.0,22,KC,5,1.0,86.0,0,0.857837
49662,4835,2023_22_SF_KC,26.0,22,KC,5,2.0,50.0,1,0.849875
49663,4860,2023_22_SF_KC,26.0,22,KC,5,1.0,6.0,1,0.871640
49664,4881,2023_22_SF_KC,NaN,22,KC,5,NaN,3.0,0,NaN

In [85]:
# Use the dropna() method to remove observations with NaN in a specific variable
# We can verify this by noticing that index 0 is now removed and index 1 is the first observation
df = nfl
NFL2023_stuffs_cleaned = df.dropna(subset=['posteam'])
NFL2023_stuffs_cleaned

Warning: total number of rows (47027) exceeds max_rows (20000). Falling back to pandas display.

,play_id,game_id,drive,week,posteam,qtr,down,half_seconds_remaining,pass,wp
1,39,2023_01_ARI_WAS,1.0,1,WAS,1,NaN,1800.0,0,0.546262
2,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262
3,77,2023_01_ARI_WAS,1.0,1,WAS,1,2.0,1770.0,1,0.539621
4,102,2023_01_ARI_WAS,1.0,1,WAS,1,3.0,1735.0,0,0.555987
5,124,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1696.0,1,0.572573
...,...,...,...,...,...,...,...,...,...,...
49660,4791,2023_22_SF_KC,26.0,22,KC,5,3.0,127.0,1,0.648316
49661,4813,2023_22_SF_KC,26.0,22,KC,5,1.0,86.0,0,0.857837
49662,4835,2023_22_SF_KC,26.0,22,KC,5,2.0,50.0,1,0.849875
49663,4860,2023_22_SF_KC,26.0,22,KC,5,1.0,6.0,1,0.871640
49664,4881,2023_22_SF_KC,NaN,22,KC,5,NaN,3.0,0,NaN

### Question 6
- Calculate the mean value of pass for each posteam when all the following conditions hold:
  - wp is greater than 20% and less than 75%;
  - down is less than or equal to 2; and
  - half_seconds_remaining is greater than 120.

In [86]:
nfl.reset_index()
# Filter the dataframe by all criteria in a single statement
multi_filter = nfl[(nfl['wp'] > 0.20) & (nfl['wp'] < 0.75) & (nfl['down'] <= 2) & (nfl['half_seconds_remaining'] > 120)]
# Calculate the mean of the filtered dataframe and group by the posteam variable
mean_pass_val = multi_filter.groupby('posteam')['pass'].mean()
round(mean_pass_val, 2)

posteam
ARI    0.46
ATL    0.46
BAL    0.58
BUF    0.54
CAR    0.46
CHI    0.48
CIN    0.62
CLE    0.54
DAL    0.58
DEN    0.50
DET    0.50
GB     0.51
HOU    0.50
IND    0.52
JAX    0.53
KC     0.61
LA     0.55
LAC    0.57
LV     0.49
MIA    0.53
MIN    0.53
NE     0.51
NO     0.50
NYG    0.52
NYJ    0.49
PHI    0.57
PIT    0.45
SEA    0.55
SF     0.53
TB     0.51
TEN    0.47
WAS    0.61
Name: pass, dtype: float64

In [87]:
NFL2023_epa = pd.read_csv('https://bcdanl.github.io/data/NFL2023_epa.csv')

### Question 7
- Create the DataFrame, NFL2023_stuffs_EPA, that includes
  - All the variables in the DataFrame, NFL2023_stuffs
  - The variables, passer, receiver, and epa, from the DataFrame, NFL2023_epa by joining the two DataFrames.
- In the resulting DataFrame, NFL2023_stuffs_EPA, remove observations with NA in passer.

In [84]:
# Merge the two dataframes on the play_id key and verify the additional variables from NFL2023_epa are included
merge_left = pd.merge(nfl, NFL2023_epa[['play_id', 'passer', 'receiver', 'epa']], on='play_id', how='left')
# Drop the observations with NaN in the passer variable
remove_nul_passer = merge_left.dropna(subset=['passer'])
remove_nul_passer

Warning: total number of rows (290469) exceeds max_rows (20000). Falling back to pandas display.

,play_id,game_id,drive,week,posteam,qtr,down,half_seconds_remaining,pass,wp,passer,receiver,epa
202,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262,D.Ridder,D.Ridder,-1.515348
204,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262,G.Smith,T.Lockett,0.043212
206,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262,J.Hurts,K.Gainwell,0.273446
207,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262,K.Pickett,G.Pickens,0.245755
209,55,2023_01_ARI_WAS,1.0,1,WAS,1,1.0,1800.0,0,0.546262,L.Jackson,I.Likely,0.620754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632546,4791,2023_22_SF_KC,26.0,22,KC,5,3.0,127.0,1,0.648316,W.Levis,D.Hopkins,1.535999
632547,4791,2023_22_SF_KC,26.0,22,KC,5,3.0,127.0,1,0.648316,P.Mahomes,NaN,1.728891
632550,4835,2023_22_SF_KC,26.0,22,KC,5,2.0,50.0,1,0.849875,P.Mahomes,T.Kelce,-0.637115
632551,4860,2023_22_SF_KC,26.0,22,KC,5,1.0,6.0,1,0.871640,P.Mahomes,M.Hardman,3.102806
632554,4881,2023_22_SF_KC,NaN,22,KC,5,NaN,3.0,0,NaN,T.Siemian,Bre.Hall,0.435069

In [67]:
nfl.nunique()

play_id                    4807
game_id                     285
drive                        34
week                         22
posteam                      32
qtr                           5
down                          4
half_seconds_remaining     1800
pass                          2
wp                        36731
dtype: int64