<a href="https://colab.research.google.com/github/brianstoner/Data-Prep-and-Mgmt/blob/main/danl_m1_exam_Stoner_Brian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
beer_mkts = pd.read_csv('https://bcdanl.github.io/data/beer_markets.csv')

In [3]:
from google.colab import data_table
data_table.enable_dataframe_formatter()

### Question 1
- *Find the top 5 beer markets in terms of the number of households that purchased beer.*
- *Find the top 5 beer markets in terms of the amount of total beer consumption.*

In [16]:
beer_mkts

Warning: total number of rows (73115) exceeds max_rows (20000). Falling back to pandas display.

,hh,_purchase_desc,quantity,brand,dollar_spent,beer_floz,price_per_floz,container,promo,market,...,age,employment,degree,cow,race,microwave,dishwasher,tvcable,singlefamilyhome,npeople
0,2000946,BUD LT BR CN 12P,1,BUD LIGHT,8.14,144.0,0.056528,CAN,False,RURAL ILLINOIS,...,50+,none,Grad,none/retired/student,white,True,True,premium,False,1
1,2003036,BUD LT BR CN 24P,1,BUD LIGHT,17.48,288.0,0.060694,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
2,2003036,BUD LT BR CN 24P,2,BUD LIGHT,33.92,576.0,0.058889,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
3,2003036,BUD LT BR CN 30P,2,BUD LIGHT,34.74,720.0,0.048250,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
4,2003036,BUD LT BR CN 36P,2,BUD LIGHT,40.48,864.0,0.046852,CAN,False,ATLANTA,...,50+,full,College,clerical/sales/service,white,True,True,basic,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73110,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,11.49,288.0,0.039896,CAN,True,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73111,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.97,288.0,0.034618,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73112,9158319,NATURAL LT BR CN 24P,1,NATURAL LIGHT,9.98,288.0,0.034653,CAN,False,RURAL VIRGINIA,...,50+,none,HS,none/retired/student,black,True,True,premium,True,2
73113,9164033,NATURAL LT BR CN 30P,1,NATURAL LIGHT,12.98,360.0,0.036056,CAN,False,SACRAMENTO,...,50+,full,College,prof,hispanic,True,True,basic,True,5plus
73114,9164155,NATURAL LT BR CN 24P,1,NATURAL LIGHT,13.49,288.0,0.046840,CAN,False,JACKSONVILLE,...,50+,full,HS,labor/craft/military/farm,white,True,True,none,True,2

In [6]:
# Count the number of unique households by market
df = beer_mkts
count_by_market = df.groupby('market')['hh'].nunique()
count_by_market
# Sort descending and limit to top 5 markets by household values
top_markets = count_by_market.sort_values(ascending = False).head(5)
top_markets

market
TAMPA        345
CHICAGO      317
PHOENIX      310
ST. LOUIS    301
HOUSTON      269
Name: hh, dtype: int64

In [7]:
# Grouping by market, find the total consumtion by ounces in the beer_floz variable
consumption_by_market = df.groupby('market')['beer_floz'].sum()
consumption_by_market
# Sort values and limit to the top 5 results
top_markets = consumption_by_market.sort_values(ascending = False).head(5)
top_markets

market
TAMPA          890418.0
PHOENIX        675318.0
MIAMI          632684.0
SAN ANTONIO    631852.0
CHICAGO        558878.0
Name: beer_floz, dtype: float64

### Question 2
- *For households that purchased BUD LIGHT at least once, what fraction of households did purchase only BUD LIGHT?*

- *For households that purchased BUSCH LIGHT at least once, what fraction of households did purchase only BUSCH LIGHT?*

- *For households that purchased COORS LIGHT at least once, what fraction of households did purchase only COORS LIGHT?*

- *For households that purchased MILLER LITE at least once, what fraction of households did purchase only MILLER LITE?*

- *For households that purchased NATURAL LIGHT at least once, what fraction of households did purchase only NATURAL LIGHT?*

- *Which beer brand does have the largest proportion of such loyal consumers?*

In [15]:
# Filter the dataframe to households that bought the product at least once
bl_filtered = df[df['brand'] == 'BUD LIGHT']
all_households = df['hh'].unique()
# Group households that appear in the foltered dataframe
only_bud_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
# Calculate the fraction of households that bought at least once to all households
fraction_only_bud_light = len(only_bud_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only BUD LIGHT is: {fraction_only_bud_light:.2f}")
# Repeat the above code with the various values in the brand variable
bl_filtered = df[df['brand'] == 'BUSCH LIGHT']
all_households = df['hh'].unique()
only_busch_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_busch_light = len(only_busch_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only BUSCH LIGHT is: {fraction_only_busch_light:.2f}")

bl_filtered = df[df['brand'] == 'COORS LIGHT']
all_households = df['hh'].unique()
only_coors_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_coors_light = len(only_coors_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only COORS LIGHT is: {fraction_only_coors_light:.2f}")

bl_filtered = df[df['brand'] == 'MILLER LIGHT']
all_households = df['hh'].unique()
only_miller_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_miller_light = len(only_miller_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only MILLER LIGHT is: {fraction_only_miller_light:.2f}")

bl_filtered = df[df['brand'] == 'NATURAL LIGHT']
all_households = df['hh'].unique()
only_natural_light = bl_filtered.groupby('hh').filter(lambda x: len(x) == df[df['hh'] == x.name].shape[0])
fraction_only_natural_light = len(only_natural_light['hh'].unique()) / len(all_households)
print(f"The fraction of households that purchased only NATURAL LIGHT is: {fraction_only_natural_light:.2f}")

The fraction of households that purchased only BUD LIGHT is: 0.30
The fraction of households that purchased only BUSCH LIGHT is: 0.05
The fraction of households that purchased only COORS LIGHT is: 0.19
The fraction of households that purchased only MILLER LIGHT is: 0.00
The fraction of households that purchased only NATURAL LIGHT is: 0.06

In [46]:
import numpy as np
paidsearch = pd.read_csv('https://bcdanl.github.io/data/paidsearch.csv')

### Question 3
- *Summarize the mean value of revenue for each group of search_stays_on and for each date.*

In [45]:
new_df = paidsearch
# Convert the date datatype from object to datetime
new_df['date'] = pd.to_datetime(new_df['date'])
# Group by search stays on and date for the mean value of revenue
mean_revenue_summary = round(new_df.groupby(['search_stays_on', 'date'])['revenue'].mean(), 2)
mean_revenue_summary

search_stays_on  date
0                2012-04-01     93650.68
                 2012-04-02    113057.92
                 2012-04-03    114255.77
                 2012-04-04    104836.69
                 2012-04-05    106881.59
                                 ...
1                2012-07-18    139383.76
                 2012-07-19    133239.08
                 2012-07-20    129653.84
                 2012-07-21    107194.27
                 2012-07-22    116001.55
Name: revenue, Length: 226, dtype: float64

### Question 4
- *Calculate the log difference between mean revenues in each group of search_stays_on. (This is the log of the average revenue in group of search_stays_on == 1 minus the log of the average revenue in group of search_stays_on == 0.)*

In [52]:
# Calculate the mean revenue for each of the search_stays_on groups
mean_revenue = new_df.groupby('search_stays_on')['revenue'].mean()
# Find the logarithm of the mean revenue for each group
log_mean_revenue = np.log(mean_revenue)
# Calculate the log difference
log_diff = log_mean_revenue.loc[1] - log_mean_revenue.loc[0]
print(f"The log difference between mean revenues for each group of search_stays_on is: {log_diff:.2f}")

The log difference between mean revenues for each group of search_stays_on is: 0.24